# site settings

copyright_start_date: 2010
description: I'm a JavaScript developer who loves open source, standards, best practices, learning, and sharing what I learn. Development is a lifestyle, not a job.
title: Michael Novotny

# build settings

baseurl: ''
exclude:
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - package.json
  - README.md
  - website.iml
permalink: /:title/
sass:
  style: compressed
timezone: America/Chicago
