# site settings

copyright_start_date: 2010
description: JavaScript developer. Open source contributor. Insatiable learner. Standards and best practices enthusiast. Development is a lifestyle, not a job.
google_analytics: UA-27106984-1
title: Michael Novotny

# build settings

baseurl: ''
exclude:
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - package.json
  - README.md
  - website.iml
gems:
  - jekyll-seo-tag
permalink: /:title/
sass:
  style: compressed
timezone: America/Chicago
